services:
  db:
    image: postgres:17.2-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=denis
      - POSTGRES_PASSWORD=denis
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: