version: "3.13"

services:
  postgres:
    image: postgres:17.2-alpine
    restart: always
    env_file:
      - .env
    expose:
      - 5432
  web:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - postgres